:sources:
  SimpleAdapter:
    :poll_interval: 300
  SampleAdapter:
    :partition_type: app    
    :poll_interval: 500

:development:
  :licensefile: settings/license.key
  :redis: 
    - 'localhost:6379'
    - 'localhost:6380'
  :syncserver: http://localhost:9292/application/
:test: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/
:production: 
  :licensefile: settings/license.key
  :redis: localhost:6379
  :syncserver: http://localhost:9292/application/